# Generated by Django 3.2 on 2023-10-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231027_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.TextField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
